sudo: false
osx_image: xcode7.1

language: python
python:
- 2.7
- 3.0
- 3.1
- 3.2
- 3.3
- 3.4
- 3.5

script:
- python setup.py build test

notifications:
  email:
    on_success: never
    on_failure: change
